# Generated by Django 3.0.2 on 2020-03-16 16:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200316_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=25)),
                ('text', models.TextField(max_length=500)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.Purchase')),
            ],
        ),
    ]
