# Generated by Django 3.0.2 on 2020-03-17 20:59

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='debts',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
    ]
